language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env: DATABASE_URL="postgres://posgres:@localhost:5432/emily_test"
install: "pip install -q -r requirements.txt"
before_script:
  - psql -c "create database emily_test;" -U postgres
  - psql -c "create user emily with password 'password'" -U postgres
script: "py.test -v emily/test/test_emily.py"
